#!/usr/bin/env php
<?php
// Generated by {{ atcodertools.version }} {{ atcodertools.url }}  (tips: You use the default template now. You can remove this line by using your custom template)
{% if mod %}
const MOD = {{ mod }};
{% endif %}
{% if yes_str %}
const YES = "{{ yes_str }}";
{% endif %}
{% if no_str %}
const NO = "{{ no_str }}";
{% endif %}

function genInputs() {
    while(($input = rtrim(fgets(STDIN))) !== false) {
        foreach (explode(' ', $input) as $v) {
            yield $v;
        }
    }
}
function getNext($gen) {
    $value = $gen->current();
    $gen->next();
    return $value;
}
$gen = genInputs();

{% if prediction_success %}
{{ input_part }}
{% else %}
// Failed to predict input format
{% endif %}
