#!/usr/bin/env php
<?php
// Generated by {{ atcodertools.version }} {{ atcodertools.url }}  (tips: You use the default template now. You can remove this line by using your custom template)
{% if mod %}
const MOD = {{ mod }};
{% endif %}
{% if yes_str %}
const YES = "{{ yes_str }}";
{% endif %}
{% if no_str %}
const NO = "{{ no_str }}";
{% endif %}
{% if prediction_success %}
function solve({{ formal_arguments }})
{
}

$inputs = [];
while (($item = fgets(STDIN)) !== false) {
    $inputs = array_merge($inputs, explode(' ', $item));
}
{{ input_part }}
solve({{ actual_arguments }});
{% else %}
// Failed to predict input format
{% endif %}
